### ISSUE TITLE
Some NITs

### ISSUE THREAD

**Issue by gregory-m** [maskimko/SelfDeployTask#1]
https://github.com/maskimko/SelfDeployTask/blob/8c1fb40c272266390e4280d7bfdfe9a8a31c0922/utils/ip.go#L24    bytes.Trim (avoid unnecessary typeconversions)
https://github.com/maskimko/SelfDeployTask/blob/8c1fb40c272266390e4280d7bfdfe9a8a31c0922/utils/cloudcheck.go#L30 regexp.MustCompile + regexp.Match (avoid unnecessary typeconversions)
https://github.com/maskimko/SelfDeployTask/blob/8c1fb40c272266390e4280d7bfdfe9a8a31c0922/server/main.go#L36 ioutil.ReadAll
https://github.com/maskimko/SelfDeployTask/blob/8c1fb40c272266390e4280d7bfdfe9a8a31c0922/server/main.go#L47 - Some bug here messageBuf[:len(messageBuf)] is same thing as messageBuf, maybe  you want use total bytes copied here.
https://github.com/maskimko/SelfDeployTask/blob/8c1fb40c272266390e4280d7bfdfe9a8a31c0922/server/main.go#L47 - You don’t need to convert it to string %s will do it: https://play.golang.org/p/XAaym9JAYzB
https://github.com/maskimko/SelfDeployTask/blob/8c1fb40c272266390e4280d7bfdfe9a8a31c0922/server/main.go#L57 regexp.MustCompile
https://github.com/maskimko/SelfDeployTask/blob/8c1fb40c272266390e4280d7bfdfe9a8a31c0922/aws/main.go#L167     err = AttachIgw(igwId, vpcId, ec2Service)
https://github.com/maskimko/SelfDeployTask/blob/8c1fb40c272266390e4280d7bfdfe9a8a31c0922/aws/main.go#L181   you can remove this line
https://github.com/maskimko/SelfDeployTask/blob/8c1fb40c272266390e4280d7bfdfe9a8a31c0922/aws/main.go#L300     err = DeleteInternetGateway(inventory.IgwId, ec2Service)

**Comment by maskimko** [comment]
Thanks for the core review. Code has been updated. PR https://github.com/maskimko/SelfDeployTask/pull/2
